version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
            # Download and cache dependencies
      - restore_cache:
          keys:
            - app-dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone-env
            . capstone-env/bin/activate
            make install
      - run:
          name: run lint
          command: |
            . capstone-env/bin/activate
            make lint
      - save_cache:
          paths:
            - ./capstone-env
          key: app-dependencies

workflows:
  default:
    jobs:
      - lint-app