version: 2.1

jobs:
  lint-app:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install prerequsites
          command: |            
             sudo apt-get install make
      - run:
          name: Install dependencies
          command: |
            make setup
            make install
      - run:
          name: Lint App
          command: |
            make lint
workflows:
  default:
    jobs:
      - lint-app